version: "3.9"

services:
  frontend:
    build: ./client
    container_name: taskmanager_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./server
    container_name: taskmanager_backend
    ports:
      - "8800:8800"
    env_file:
      - ./server/.env
    restart: unless-stopped